#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
    if ! getent group quantum > /dev/null 2>&1
    then
        addgroup --system quantum >/dev/null
    fi

    if ! getent passwd quantum > /dev/null 2>&1
    then
        adduser --system --home /var/lib/quantum --ingroup quantum --no-create-home --shell /bin/bash quantum
    fi

    chown quantum:quantum -R /var/lib/quantum /var/log/quantum
    chmod 0700 /var/log/quantum
fi

#DEBHELPER#
